name: Python Build MLBstats API 

on:
  push:
    branches:
     - main
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade pytest
          python3 -m pip install --upgrade build
          python3 -m pip install --upgrade requests
      - name: Test with pytest
        run: |
          python3 -m pytest tests/*
      - name: build and install
        run: |
          python3 -m build
          python3 -m pip install .
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}