name: Catch unexpected keyword arguments

on:
  schedule:
    # Run every six hours
    - cron:  '0 17,23 * * *'

jobs:
  catch_errors_and_report:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]


    steps:
      - uses: actions/checkout@develop
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip                    
          python3 -m pip install --upgrade slack_sdk          
      - name: Test and report
        run: |
          script -q /dev/null python3 -m pytest --tb=no tests/* | python3 ./.github/scripts/pytest_report_issues.py ${{ secrets.PR_CHANNEL }} ${{ secrets.SLACK_WEBCLIENT_TOKEN }}