name: Report Issue Creation

on:
  issues:
    types: [opened]

jobs:
  reportNewIssue:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade slack_sdk          
      - name: Report Issue
        env: 
          ISSUE_URL: ${{ github.event.issue.html_url }}
          ISSUE_USER: ${{ github.event.issue.user.login }}
          ISSUE_USER_IMAGE: ${{ github.event.issue.user.avatar_url }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_TIME: ${{ github.event.issue.created_at }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_REPO: ${{ github.event.repository.full_name }}
          ISSUE_REPO_URL: ${{ github.event.repository.html_url }}

        run: |
          python3 ./.github/scripts/issueslackbot.py ${{ secrets.ISSUE_CHANNEL }} ${{ secrets.SLACK_WEBCLIENT_TOKEN }}
 