name: Report push request url

on: pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade slack_sdk          
      - name: Report PR url
        env: # Or as an environment variable
          credentials: ${{ secrets.SLACK_WEBCLIENT_TOKEN }}
        run: |
          python3 utils/prslackbot.py "$SLACK_WEBCLIENT_TOKEN" github.event.pull_request.html_url
